server:
  port: 9091

spring:
  datasource:
    dynamic:
      datasource:
        master:
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          url: jdbc:sqlserver://192.168.1.201:1433; DatabaseName=bs_yjyy
          username: sa
          password: bsoft

swagger:
  enabled: false
